### PR TITLE
The current version is lacking the "AnsiConsole.Confirm" prompt. So I created a function following your conventions to include it.

### PR DESCRIPTION
**Pull request by fmotion1**
The prompt I'm referring to is here: https://spectreconsole.net/prompts/text - under the "Confirmation" section. It's basically a confirmation prompt of which you can only select yes or no [Y/n]. 

Before I came across your repository I had my own wrapper for Spectre, but it was nowhere near as complete as yours. However, several scripts of mine rely on my own wrapper for `AnsiConsole.Confirm`, and as of now it's not implemented in this module. I'd like to completely switch over to `PwshSpectreConsole` - so that's why I'm contributing! 

This is literally the first pull request I've ever made, so if I did something wrong please let me know. 

One thing I'm not sure you'll approve of is the variable name for the prompt. It looks like all your functions are using $Title. I went with $Prompt, since it makes more sense in the context of this function to me. But the final variable name is irrelevant to me - change it if you must. :)

I hope you like the addition. It's nothing groundbreaking but does fill a small gap in coverage.

### CODE REVIEW

**Comment by ShaunLawrie** [comment]
Nice! Thanks yeah I don't mind the prompt parameter name it makes sense in the context.

Half the reason I made the module was because of the pain of dealing with the async code blocking ctrl-c from exiting the script while a spectre prompt was running. I would be halfway through executing a script and not be able to cancel it without closing the terminal window 😆 I've just updated this to use `Invoke-SpectrePromptAsync` which handles the async code synchronously with the best hack I could find in powershell to make it work.

I also added the default color scheme support for `Set-SpectreColors` and the option of changing the default answer between "yes and no" so for something like "Do you want to delete these 1000 files?" you can have the default answer "n".

**Comment by ShaunLawrie** [comment]
https://pwshspectreconsole.com/reference/prompts/read-spectreconfirm/

**Comment by ShaunLawrie** [comment]
Try the latest version, I just chucked in a converter for colors so all the stuff I have should handle hex. I was already dealing with the colors as strings so I just needed to update the parameter validator to validate the hex pattern was legit and convert all string values to a color object with `Convert-ToSpectreColor`  https://github.com/ShaunLawrie/PwshSpectreConsole/commit/1923bb316d669390d364632e7d4a819a740bc43f

**Comment by fmotion1** [comment]
I commented on the commit: https://github.com/ShaunLawrie/PwshSpectreConsole/commit/1923bb316d669390d364632e7d4a819a740bc43f

Just wondering if `Convert-ToSpectreColor` is supposed to be public facing? It's not exported in the manifest. If not, I'm unsure how to use HEX in I.E a BarChart:

```powershell
$data = @(
    @{ Label = "Apples"; Value = 10; Color = Convert-ToSpectreColor -Color #12D34A },
    @{ Label = "Oranges"; Value = 5; Color = Convert-ToSpectreColor -Color #F3D757 },
    @{ Label = "Bananas"; Value = 3; Color = Convert-ToSpectreColor -Color #F35757 }
)
Format-SpectreBarChart -Data $data -Title "Fruit Sales" -Width 50
```

What's the proper way to accomplish the above without `Convert-ToSpectreColor`?

**Comment by ShaunLawrie** [comment]
🤦‍♂️I intended to just use that function internally but I forgot to use it in the chart functions to parse the colors.
I was trying to make it so you could pass any format, the color object, the hex as a string or the color name.

I just pushed a fix for this.

image

**Pull request merged**
