### PR TITLE
Updates to Format-SpectreTable and Format-SpectreJson

### LINKED ISSUE #24: Bug Format-SpectreTable enumerating [ICollection]
opening an issue just incase someone else also runs into it.

i found a bug in my code for Format-SpectreTable and there doesnt seem to be an obvious solution that would cover all scenarios.

the first command runs with the latest preview, the second runs my local test with Format-Table instead of Select-Object for formatting.
image

The problem seem to be that some properties are unrolled and that doesn't seem to be apart of the formatting file but some internal db in Format-Table or something.

[BaseFormattingCommand](https://github.com/PowerShell/PowerShell/blob/f0076b9d883aa0ed07fb2a5c2be5f38f5d945e1e/src/System.Management.Automation/FormatAndOutput/common/BaseFormattingCommand.cs#L110)

[GetExpansionState](https://github.com/PowerShell/PowerShell/blob/f0076b9d883aa0ed07fb2a5c2be5f38f5d945e1e/src/System.Management.Automation/FormatAndOutput/common/BaseFormattingCommand.cs#L153-L157)

I have not found a good way to detect this, `[ICollection]` seems to be the type but there are different propertynames for different types..

While it certainly is possible to add the ones we find and unroll them.. i thought it might be easier to just rip out the values from Format-Table and let that worry about enumeration.

I'm still testing so it's not really ready, but i might push a few changes.

the new method is still very untested so need a little time.

Current approach uses something like this,
[Get-TableData](https://gist.github.com/trackd/bde8266b15e50c71246696517f04ca48)

### PR DESCRIPTION
**Pull request by trackd**
- refactor to use `Format-Table` instead of _FormatData_ to get properties and formatting.
- fixes #24 
- extend functionality of `Format-SpectreJson`, testing out some neat stuff.
- added ArgumentTransformationAttribute for Colors
- Extend `Get-SpectreImageExperimental` with an `-ImgUrl` parameter.

`Format-SpectreJson`
if it detects a '.json' file (e.g `Get-Childitem -File *.json | fsj`) it will render it.
it tries to detect streams of json as well, e.g (`Get-Childitem -File *.json | gc | fsj`)
or something like:
`(iwr https://httpbin.org/get).Content | fsj`
fsj

i had to disable some tests, i'll try and get some new tests to replace them.

### CODE REVIEW

**Comment by trackd** [comment]
i havnt fully tested the Format-Table parameters i've added, they work but i think Spectre.Console overrides a few of them (like `-Wrap` and `-AutoSize`)

**Comment by trackd** [comment]
@ShaunLawrie i think this might be ready.

Do we need more tests?

**Comment by ShaunLawrie** [comment]
lgtm, ready to merge when you're happy. Nice tweak adding the image from remote source.

**Comment by trackd** [comment]
Removed `-Expand` and `-AutoSize`, 
kept `-Wrap` it technically doesn't do anything at the moment but there is an open issue in spectre.console.
it doesn't really matter that it's there but when its fixed in Spectre it should automatically work for us.

cleaned up a bit and did some tweaks with better error handling etc.

it's ready to merge to prerelease

**Comment by ShaunLawrie** [comment]
Nice!

**Pull request merged**
